---
- name: Generate a random user password
  shell: python -c "import random; import string; print ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(24))"
  register: randpass

- name: Create non-root user accounts
  user:
    name: "{{ item.name }}"
    password: "{{ randpass.stdout }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | default(omit) }}"
    append: yes
    state: "{{ item.state | default('present') }}"
    expires: "{{ item.expiry | default(omit) }}"
  with_items:
    - "{{ defined_users }}"

- name: Create SSH directory in home
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    owner: "{{ item.name }}"
    mode: 0700
  with_items:
    - "{{ defined_users }}"

- name: Create authorized_keys file
  copy:
    src: ~/.ssh/id_rsa.pub
    dest: "/home/{{ item.name }}/.ssh/authorized_keys"
    owner: "{{ item.name }}"
    mode: 0600
  with_items:
    - "{{ defined_users }}"
