---
- name: Update droplet to latest versions of everything
  yum:
    name: '*'
    state: latest

- name: Rebooting droplet (regardless...)
  shell: sleep 2 && /sbin/shutdown -r now "Reboot required following updates"
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for droplet to reboot
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 30
    timeout: 300
